export const PERFORMANCES = [
  {
    day: 'WEDNESDAY',
    datetime: '16.04.2025 | 19:30',
    title: 'A Midsummer Night\'s Dream',
    author: 'William Shakespeare',
    intermission: 'with intermission',
    duration: '2 hours 15 minutes (intermission after the third act)',
    ticketsUrl: '#',
  },
  {
    day: 'THURSDAY',
    datetime: '17.04.2025 | 19:30',
    title: 'Romeo and Juliet',
    author: 'William Shakespeare',
    intermission: 'without intermission',
    duration: '1 hour 30 minutes',
    ticketsUrl: '#',
  },
  {
    day: 'SATURDAY',
    datetime: '19.04.2025 | 16:00',
    title: 'Carnival of the Animals',
    author: 'Poulenc/Ridout/Saint-Saëns',
    intermission: 'without intermission',
    duration: '1 hour 10 minutes',
    ticketsUrl: '#',
  },
  {
    day: 'SATURDAY',
    datetime: '19.04.2025 | 19:30',
    title: 'The Magic Flute',
    author: 'Wolfgang Amadeus Mozart',
    intermission: 'with intermission',
    duration: '2 hours 10 minutes (intermission after the first act)',
    ticketsUrl: '#',
  },
];
