export const HISTORY_PAGE_CONTENT = {
  firstSection: {
    title: 'Gia đình nghệ nhân họ Phạm - Những người sáng lập Rối Tế Tiêu',
    subTitle: 'Gia đình nghệ nhân họ Phạm - ba thế hệ nghệ nhân',
    content: 'Suốt gần 70 năm qua, gia đình nghệ nhân Phạm Văn Bể đã là lực lượng nòng cốt trong việc gìn giữ và phát triển nghệ thuật Rối cạn Tế Tiêu, trở thành một phần không thể thiếu trong đời sống văn hóa của vùng Đại Nghĩa, Mỹ Đức. Qua ba thế hệ nghệ nhân – từ Phạm Văn Bể, Phạm Công Bằng đến thế hệ kế cận hôm nay – phường rối được duy trì với lòng yêu nghề sâu sắc và kỹ năng nghệ thuật tinh tế, luôn ý thức trách nhiệm bảo tồn và phát huy một di sản quý báu của đồng bằng Bắc Bộ.',
  },

  secondSection: {
    title: 'Sự khởi đầu: Nghệ nhân Phạm Văn Bể và sự hồi sinh Phường rối',
    content: 'Sau chiến dịch Điện Biên Phủ, năm 1956, nghệ nhân Phạm Văn Bể trở về quê nhà trong nỗi lo lắng rằng nghệ thuật rối cạn Tế Tiêu sẽ thất truyền. Ông tìm đến cụ Lê Năng Nhượng – nghệ nhân cao tuổi còn giữ nghề – để xin học. Với tài năng sẵn có và lòng đam mê, ông nhanh chóng nắm vững cách chế tác quân rối, kỹ thuật diễn trò và các tích trò cổ truyền. Cùng cụ Ba Nhượng, ông tái lập Phường Rối cạn Tế Tiêu, khôi phục những con rối đã cũ, sáng tạo thêm trò mới phù hợp với thời đại, gây dựng lại sân khấu rối giữa lòng làng quê đang hồi sinh sau chiến tranh.</br></br> Trên nền đất làng quê vừa hồi sinh sau chiến tranh, họ đã dựng lại sân khấu rối giữa lòng dân, thổi sức sống mới vào từng con rối gỗ, từng tích trò thấm đẫm tiếng cười và những bài học nhân văn sâu sắc. Bằng đôi tay khéo léo và tấm lòng nhiệt thành, hai nghệ nhân Phạm Văn Bể và Lê Năng Nhượng đã chung tay hồi sinh phường rối Tế Tiêu, đưa loại hình nghệ thuật truyền thống này trở lại đời sống văn hóa cộng đồng, góp phần làm rạng rỡ thêm cho bức tranh văn hóa phong phú của vùng đồng bằng Bắc Bộ.',
  },

  thirdSection: {
    title: 'Phát triển và lan toả danh tiếng',
    content: 'Từ những năm 1960, Phường Rối cạn Tế Tiêu không ngừng lớn mạnh, trở thành một điểm sáng trong phong trào văn hóa nghệ thuật dân gian Việt Nam. Các tiết mục biểu diễn như "Quan Vũ trảm lục tướng", "Đào viên kết nghĩa", "Chiến dịch Mỹ Đức" vừa đậm đà bản sắc cổ truyền, vừa phản ánh đời sống xã hội đương đại, đã chạm tới trái tim của đông đảo khán giả. Phường không chỉ tham gia nhiều kỳ liên hoan múa rối toàn miền Bắc mà còn có cơ hội giao lưu biểu diễn với các đoàn nghệ thuật nước ngoài đến từ Tiệp Khắc, Liên Xô và Trung Quốc. Tên tuổi Phường rối cạn Tế Tiêu dần dần trở thành biểu tượng tiêu biểu cho nghệ thuật rối dân gian Việt Nam.</br></br>  Nhờ những nỗ lực bền bỉ và tâm huyết của các thế hệ nghệ nhân, Phường đã đạt được nhiều thành tích nổi bật, góp phần đưa nghệ thuật rối cạn truyền thống đến gần hơn với công chúng trong nước cũng như bạn bè quốc tế.</br></br>  Từ năm 1961 đến 1971, Phường rối cạn Tế Tiêu bước vào thời kỳ hưng thịnh, với nhiều hoạt động biểu diễn, đào tạo thế hệ trẻ và tham gia các sự kiện văn hóa lớn cấp miền Bắc. Phường trở thành một trong những đại diện tiêu biểu cho nghệ thuật múa rối dân gian Việt Nam thời kỳ này.</br></br>  Tuy nhiên, từ năm 1975 trở về trước, do ảnh hưởng của cuộc kháng chiến chống Mỹ, hoạt động của phường rối bị gián đoạn, nhiều nghệ nhân tham gia chiến đấu, dẫn đến tình trạng suy thoái, đình trệ kéo dài sau ngày đất nước thống nhất.  Giai đoạn 1979–1985, nghệ nhân Phạm Văn Bể đã khôi phục lại Phường rối với sự chung tay của cộng đồng, mở ra thời kỳ tái thiết và hồi sinh mạnh mẽ.</br></br>  Từ năm 1986 đến 2010, Phường rối cạn Tế Tiêu không ngừng phát triển, sáng tác nhiều tích trò mới, tham gia các hoạt động văn hóa lớn, khẳng định vị thế trong phong trào nghệ thuật dân gian. Năm 1995, phường chính thức gia nhập Liên chi hội Múa rối UNIMA Việt Nam, đánh dấu bước tiến quan trọng trong quá trình hội nhập và chuyên nghiệp hóa.',
  },

  fourthSection: {
    title: 'Lịch sử hình thành',
    content: 'Nghệ thuật Rối Cạn Tế Tiêu có nguồn gốc từ nghệ thuật múa rối nước, được hình thành từ thế kỷ 16, 17. Nghệ thuật Rối Cạn Tế Tiêu được hình thành và phát triển từ những năm đầu thế kỷ 20 tại xã Đại Nghĩa, huyện Mỹ Đức, Hà Nội. Đến nay, nghệ thuật Rối Cạn Tế Tiêu đã trải qua hơn 100 năm hình thành và phát triển.',
  },

  fifthSection: {
    title: 'Một di sản sống động giữa thời hiện đại',
    content: 'Ngày nay, Rối cạn Tế Tiêu không chỉ còn là ký ức văn hóa của làng quê Bắc Bộ mà đã trở thành biểu tượng sinh động cho sức sống bền bỉ của nghệ thuật truyền thống Việt Nam. Trên nền tảng gìn giữ bản sắc cổ truyền, Phường rối Tế Tiêu không ngừng sáng tạo, đổi mới nội dung biểu diễn nhằm phù hợp với nhịp sống đương đại, đồng thời duy trì không gian trình diễn cố định và bảo tồn hàng trăm quân rối cùng các tích trò quý giá. Qua ba thế hệ nghệ nhân nối tiếp, Phường rối Tế Tiêu đã khẳng định tình yêu nghệ thuật sâu sắc và khát vọng mạnh mẽ đưa nghệ thuật rối cạn vươn xa, sống mãi trong lòng công chúng hôm nay và mai sau.</br></br>  Nhằm tiếp tục bảo tồn và lan tỏa giá trị của nghệ thuật rối cạn, nghệ nhân Phạm Công Bằng đã chủ động đề xuất với chính quyền địa phương về việc xây dựng Bảo tàng Rối cạn Tế Tiêu ngay tại quê hương. Dự án này nhận được sự ủng hộ từ các cấp chính quyền và các tổ chức bảo tồn văn hóa, với mục tiêu tạo ra một không gian lưu giữ, trưng bày, và trải nghiệm gắn liền với nghệ thuật múa rối truyền thống. Công trình bảo tàng đã được khởi công và hiện đang trong quá trình hoàn thiện, dự kiến sẽ khánh thành và đưa vào hoạt động vào tháng 6 năm 2025.</br></br>  Bảo tàng Rối cạn Tế Tiêu được thiết kế theo mô hình không gian mở, kết hợp giữa khu vực trưng bày hiện vật và sân khấu biểu diễn. Bên cạnh việc giới thiệu các tác phẩm rối đặc sắc, bảo tàng còn trưng bày nhiều loại rối cổ truyền thống khác, mang đến cho du khách cái nhìn đa chiều về lịch sử và nghệ thuật múa rối Việt Nam. Tại đây, khách tham quan có cơ hội tận mắt chứng kiến quá trình chế tác rối gỗ của các nghệ nhân, tìm hiểu ý nghĩa văn hóa, lịch sử ẩn sau mỗi nhân vật rối thông qua hệ thống tư liệu trưng bày phong phú.</br></br>  Với sự nỗ lực bền bỉ của nghệ nhân và các thành viên trong phường rối cùng cộng đồng địa phương, sự đồng hành từ các cơ quan văn hóa, Bảo tàng Rối cạn Tế Tiêu hứa hẹn sẽ trở thành điểm sáng trong công tác bảo tồn và phát huy di sản văn hóa phi vật thể quốc gia. Đây không chỉ là niềm tự hào của người dân địa phương mà còn là minh chứng cho sức sống mạnh mẽ, trường tồn của nghệ thuật truyền thống Việt Nam trong dòng chảy hiện đại.',
  },
};
